name: GoGram (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '3 1 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run script
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          TG_FLOOD_SLEEP_THRESHOLD: ${{ secrets.TG_FLOOD_SLEEP_THRESHOLD }}
          TG_MESSAGE_LINK: ${{ secrets.TG_MESSAGE_LINK }}
        run: |
          echo "Beginning GoGram test"
          mkdir -p outputs
          cd scripts/golang/
          go mod tidy && go get github.com/amarnathcjd/gogram@master && go run .
          cd ../../
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <GoGram>"
          git add scripts/golang/go.mod scripts/golang/go.sum
          git commit -m "dependency"

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <GoGram>"
          git add outputs/ -A
          git commit -m "update GoGram bench"
          git pull origin master
          git push origin master
