name: GoGram (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '3 1 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_THRESHOLD: ${{ secrets.FLOOD_WAIT_THRESHOLD }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning GoGram test"
          mkdir -p outputs
          cd scripts/golang/gogram
          go mod tidy && go get github.com/amarnathcjd/gogram@master && go run .
          cd ../../../

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <GoGram>"
          git add scripts/golang/goggram/ outputs/ -A
          git commit -m "update GoGram bench"
          git pull origin master
          git push origin master
