name: Hydrogram (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_THRESHOLD: ${{ secrets.FLOOD_WAIT_THRESHOLD }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning Pyrogram test"
          mkdir -p outputs
          pip install --force-reinstall https://github.com/hydrogram/hydrogram/archive/d546da5.zip TgCrypto==1.2.5 > /dev/null 2>&1
          sed -i s/pyrogram/hydrogram/g scripts/python/p2.py
          P=$(python scripts/python/p2.py)
          pip uninstall -y hydrogram tgcrypto > /dev/null 2>&1
          echo "${P}" > outputs/hydrogram.json

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <Hydrogram>"
          git add outputs/ -A
          git commit -m "update Hydrogram bench"
          git pull origin master
          git push origin master
