name: MadeLineProto (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '33 2 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: hub.madelineproto.xyz/danog/madelineproto:latest
          options: >-
            -v ${{ github.workspace }}:/app
            -e TG_API_ID
            -e TG_API_HASH
            -e TG_BOT_TOKEN
            -e TG_SESSION
            -e TG_FLOOD_SLEEP_THRESHOLD
            -e TG_MESSAGE_LINK
          run: |
            echo "Beginning MadeLineProto test"
            mkdir -p outputs
            php /app/scripts/php/madelineproto/mp1.php
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          TG_FLOOD_SLEEP_THRESHOLD: ${{ secrets.TG_FLOOD_SLEEP_THRESHOLD }}
          TG_MESSAGE_LINK: ${{ secrets.TG_MESSAGE_LINK }}

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <MadeLineProto>"
          git add outputs/ -A
          git commit -m "update MadeLineProto bench"
          git pull origin master
          git push origin master
