name: MadeLineProto (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '33 2 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: hub.madelineproto.xyz/danog/madelineproto:latest
          options: >-
            -v ${{ github.workspace }}:/app
            -e API_ID
            -e API_HASH
            -e BOT_TOKEN
            -e TG_SESSION
            -e FLOOD_WAIT_THRESHOLD
            -e MESSAGE_LINK
          run: |
            echo "Beginning MadeLineProto test"
            mkdir -p outputs
            php /app/scripts/php/madelineproto/mp1.php
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_THRESHOLD: ${{ secrets.FLOOD_WAIT_THRESHOLD }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <MadeLineProto>"
          git add outputs/ -A
          git commit -m "update MadeLineProto bench"
          git pull origin master
          git push origin master
