name: mtkruto

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.9

      - name: Run script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_SLEEP_TIME: ${{ secrets.FLOOD_WAIT_SLEEP_TIME }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning MTKruto test"
          mkdir -p out
          cd src/mtkruto
          rm deno.lock
          echo "{}" > deno.json
          deno install jsr:@mtkruto/mtkruto
          deno -A m4.ts
          cd ../../..

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git add sec/mtkruto out/ -A
          LIBRARY="MTKruto" ./.github/_commit.sh
          git pull origin master
          git push origin master
