name: Pyrogram (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_SLEEP_TIME: ${{ secrets.FLOOD_WAIT_SLEEP_TIME }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning Pyrogram test"
          mkdir -p outputs
          pip install --force-reinstall Pyrogram==2.0.106 TgCrypto==1.2.5 > /dev/null 2>&1
          P=$(python scripts/python/p2.py)
          pip uninstall -y pyrogram tgcrypto > /dev/null 2>&1
          echo "${P}" > outputs/pyrogram.json

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <Pyrogram>"
          git add outputs/ -A
          git commit -m "update Pyrogram bench"
          git pull origin master
          git push origin master
