name: PyroBlack (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '3 3 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          TG_FLOOD_SLEEP_THRESHOLD: ${{ secrets.TG_FLOOD_SLEEP_THRESHOLD }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning Pyrogram test"
          mkdir -p outputs
          pip install --force-reinstall pyroblack https://github.com/eyMarv/tgcrypto-pyroblack/archive/6c634e2.zip > /dev/null 2>&1
          P=$(python scripts/python/p2.py)
          pip uninstall -y pyroblack TgCrypto-pyroblack > /dev/null 2>&1
          echo "${P}" > outputs/pyroblack.json

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <PyroBlack>"
          git add outputs/ -A
          git commit -m "update PyroBlack bench"
          git pull origin master
          git push origin master
