name: PyTDbot (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '3 4 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          TG_FLOOD_SLEEP_THRESHOLD: ${{ secrets.TG_FLOOD_SLEEP_THRESHOLD }}
          TG_MESSAGE_LINK: ${{ secrets.TG_MESSAGE_LINK }}
        run: |
          echo "Beginning Pytdbot test"
          mkdir -p outputs
          pip install --force-reinstall Pytdbot tdjson > /dev/null 2>&1
          python scripts/python/t3.py
          pip uninstall -y Pytdbot tdjson > /dev/null 2>&1

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <Pytdbot>"
          git add outputs/ -A
          git commit -m "update Pytdbot bench"
          git pull origin master
          git push origin master
