name: pytdbot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_SLEEP_TIME: ${{ secrets.FLOOD_WAIT_SLEEP_TIME }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning Pytdbot test"
          mkdir -p out
          pip install --no-cache-dir --force-reinstall --upgrade Pytdbot==0.9.1 tdjson==1.8.46 > /dev/null 2>&1
          python src/pytdbot/main.py
          pip uninstall -y Pytdbot tdjson > /dev/null 2>&1

      - name: Commit and push changes
        run: |
          LIBRARY="Pytdbot" ./.github/_commit.sh
