name: telethon

on:
  workflow_dispatch:
  schedule:
    - cron: "3 13 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          FLOOD_WAIT_SLEEP_TIME: ${{ secrets.FLOOD_WAIT_SLEEP_TIME }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning Telethon test"
          mkdir -p out
          pip install --no-cache-dir --force-reinstall --upgrade Telethon cryptg==0.5.0.post0 > /dev/null 2>&1
          T=$(python src/telethon/main.py)
          pip uninstall -y telethon cryptg > /dev/null 2>&1
          echo "${T}" > out/telethon.json

      - name: Commit and push changes
        run: |
          LIBRARY="Telethon" ./.github/_commit.sh
